apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgres-haproxy-port-forward-$SUFFIX
  namespace: $NAMESPACE
data:
  haproxy.cfg: |-
    global
    defaults
        timeout connect 30s
        timeout client 30s
        timeout server 30s

    frontend frontend
        bind 0.0.0.0:5432
        default_backend backend

    backend backend
        mode tcp
        server upstream $DATABASE_HOST:$DATABASE_PORT
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: postgres-forward-pod-$SUFFIX
  name: postgres-forward-pod-$SUFFIX
  namespace: $NAMESPACE
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - command:
        - haproxy
        - -f
        - /usr/local/etc/haproxy/haproxy.cfg
        - -V
      image: haproxy:1.7-alpine
      name: postgres-forward-pod
      resources: {}
      volumeMounts:
        - mountPath: /usr/local/etc/haproxy/
          name: postgres-haproxy-port-forward
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsUser: 1000
        runAsGroup: 1000
  restartPolicy: Always
  volumes:
    - name: postgres-haproxy-port-forward
      configMap:
        name: postgres-haproxy-port-forward-$SUFFIX
status: {}
